version: '3.8'

volumes:
  app_data:
  postgres_data:

services:
  
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file: ".prod.env"
     
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=require

